# Generated by Django 4.2.11 on 2024-11-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0085_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('match_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sport_type', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('seats', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='sportdate',
            name='SportVenue',
        ),
        migrations.RemoveField(
            model_name='sportseattype',
            name='SportDate',
        ),
        migrations.RemoveField(
            model_name='sporttickets',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='sportvenue',
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='SportDate',
        ),
        migrations.DeleteModel(
            name='SportSeatType',
        ),
        migrations.DeleteModel(
            name='SportTickets',
        ),
        migrations.DeleteModel(
            name='SportVenue',
        ),
    ]
