# Generated by Django 4.2.11 on 2024-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0088_visitingticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingticket',
            name='ticket_id',
            field=models.CharField(default=2, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
