# Generated by Django 4.2.6 on 2024-12-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0091_college_school_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('institute_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('choice_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='address',
        ),
        migrations.RemoveField(
            model_name='college',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='college',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='school',
            name='num_classes',
        ),
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.RemoveField(
            model_name='university',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='university',
            name='num_departments',
        ),
        migrations.RemoveField(
            model_name='university',
            name='num_rank',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.university')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.school')),
            ],
        ),
    ]
