# Generated by Django 4.2.6 on 2024-12-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0093_alter_class_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='class_n',
        ),
    ]
