# Generated by Django 4.2.6 on 2024-12-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0097_admission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
