# Generated by Django 4.2.6 on 2024-12-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0098_delete_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(limit_choices_to={'institute_type': 'University'}, on_delete=django.db.models.deletion.CASCADE, to='application.institute')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(limit_choices_to={'institute_type': 'School'}, on_delete=django.db.models.deletion.CASCADE, to='application.institute')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(limit_choices_to={'institute_type': 'College'}, on_delete=django.db.models.deletion.CASCADE, to='application.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('college_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.collegesubject')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.institute')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.schoolclass')),
                ('university_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.universitydepartment')),
            ],
        ),
    ]
