# Generated by Django 4.2.6 on 2024-12-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0099_institute_universitydepartment_schoolclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], max_length=10),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='application.institute')),
            ],
        ),
    ]
