# Generated by Django 4.2.6 on 2024-12-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0100_alter_institute_institute_type_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolClass',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='UniversityDepartment',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='CollegeSubject',
            new_name='Subject',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
