# Generated by Django 4.2.6 on 2024-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0104_collegesubject_schoolclass_universitydepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], max_length=50)),
            ],
        ),
    ]
