# Generated by Django 4.2.6 on 2024-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0105_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='school',
        ),
        migrations.RemoveField(
            model_name='universitydepartment',
            name='university',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='institution_type',
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CollegeSubject',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.DeleteModel(
            name='UniversityDepartment',
        ),
    ]
