# Generated by Django 4.2.6 on 2024-12-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0107_institutiontype_delete_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
