# Generated by Django 4.2.6 on 2024-12-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0109_university_school_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='university',
            name='institution_type',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='InstitutionType',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
