# Generated by Django 4.2.6 on 2024-12-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0111_college_institutiontype_school_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
