# Generated by Django 4.2.6 on 2024-12-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0114_admissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('class_subject_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.schoolclass')),
                ('institution_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.school')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.institutiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionForm',
        ),
    ]
