# Generated by Django 4.2.6 on 2024-12-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0115_admission_delete_admissionform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegesubject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='universitydepartment',
            old_name='department_name',
            new_name='name',
        ),
    ]
