# Generated by Django 4.2.6 on 2024-12-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0116_rename_subject_name_collegesubject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegesubject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='name',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='universitydepartment',
            old_name='name',
            new_name='department_name',
        ),
    ]
